/* DO NOT EDIT, file generated by nestjs-i18n */

import { Path } from "nestjs-i18n-telegraf";
export type I18nTranslations = {
    "common": {
        "message": string;
        "button": string;
    };
};
export type I18nPath = Path<I18nTranslations>;
